# Generated by Django 5.0.2 on 2024-12-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsedSparePartsOptions',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_title', models.CharField(max_length=255)),
                ('option_url', models.URLField()),
            ],
        ),
    ]
