# Generated by Django 5.0.2 on 2025-01-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCars',
            fields=[
                ('used_cars_id', models.AutoField(primary_key=True, serialize=False)),
                ('used_car_title', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
