# Generated by Django 5.0.2 on 2025-02-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0006_alter_relatedspareparts_related_spare_part_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedSpareParts',
        ),
    ]
