# Generated by Django 5.0.2 on 2025-02-07 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0007_delete_relatedspareparts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedSpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonPages.sparepart')),
            ],
        ),
    ]
