# Generated by Django 5.1.6 on 2025-02-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0009_usedcars_image1_usedcars_image2_usedcars_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcars',
            name='company',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
