# Generated by Django 5.1.6 on 2025-03-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0011_sparepart_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='related_spare_parts',
            field=models.ManyToManyField(blank=True, to='commonPages.sparepart'),
        ),
    ]
