# Generated by Django 5.0.2 on 2025-02-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0002_usedcars'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('spare_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('spare_part_title', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='usedcars',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='used_cars_images/'),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='used_cars_images/'),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='used_cars_images/'),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='used_cars_images/'),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='used_cars_images/'),
        ),
    ]
