# Generated by Django 5.0.2 on 2025-02-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0003_sparepart_usedcars_image1_usedcars_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedcars',
            old_name='image5',
            new_name='backSideImage',
        ),
        migrations.RenameField(
            model_name='usedcars',
            old_name='image4',
            new_name='interiorView',
        ),
        migrations.RenameField(
            model_name='usedcars',
            old_name='image3',
            new_name='leftSideView',
        ),
        migrations.RenameField(
            model_name='usedcars',
            old_name='image1',
            new_name='mainImage',
        ),
        migrations.RenameField(
            model_name='usedcars',
            old_name='image2',
            new_name='rightSideView',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='milage',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='extraImage',
            field=models.ImageField(blank=True, null=True, upload_to='used_cars_images/'),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='extraImage',
            field=models.ImageField(blank=True, null=True, upload_to='used_cars_images/'),
        ),
    ]
