# Generated by Django 5.0.2 on 2025-02-07 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0004_rename_image5_usedcars_backsideimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepart',
            old_name='extraImage',
            new_name='image',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RelatedSpareParts',
            fields=[
                ('related_spare_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('related_spare_part_title', models.CharField(max_length=100)),
                ('related_spare_part_image', models.ImageField(blank=True, null=True, upload_to='used_cars_images/')),
                ('related_spare_part_url', models.URLField()),
                ('spare_part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonPages.sparepart')),
            ],
        ),
    ]
