# Generated by Django 5.0.2 on 2025-02-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0005_rename_extraimage_sparepart_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedspareparts',
            name='related_spare_part_image',
            field=models.ImageField(blank=True, null=True, upload_to='spare_parts_images/'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spare_parts_images/'),
        ),
    ]
