# Generated by Django 5.1.6 on 2025-02-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0008_relatedspareparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcars',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='used_cars_images/'),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='used_cars_images/'),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='used_cars_images/'),
        ),
    ]
