# Generated by Django 5.1.6 on 2025-02-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonPages', '0010_usedcars_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='company',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
